---
baseURL: "https://kotsio.netlify.com"
languageCode: "en-us"
title: "Kots.io"
theme: "hugo-whisper-theme"
metadataformat: "yaml"
canonifyurls: true
description: "Documentation and knowledgebase for Replicated."
googleAnalytics: ""

# Hugo configuration
pygmentsCodeFences: true
pygmentsStyle: "monokai"

Params:
  author: "Kots"
  copyright: "Replicated, Inc"
  homepage_intro: "Kots is a kubectl plugin to help manage Kubernetes Off-The-Shelf software"

  # matomo:
  #   host: "localhost:4000"
  #   site: "2"

  favicon: ""
  pagetitle: "Kots.io"
  permalink: "#"

menu:
  main:
    - Name: "Guided walkthroughs"
      Weight: 1
      URL: "/guides/"
    - Name: "API reference"
      Weight: 2
      URL: "/api/"
    - Name: "Documentation"
      Weight: 3
      URL: "/docs/"
---