---
baseURL: "https://kots.io"
languageCode: "en-us"
title: "Kots.io"
theme: "hugo-whisper-theme"
metadataformat: "yaml"
canonifyurls: true
description: "Documentation for Replicated Kots."
googleAnalytics: ""


# Hugo configuration
pygmentsCodeFences: true
pygmentsStyle: "monokai"

staticDir:
    - ./static

Params:
  author: "Kots"
  copyright: "Replicated, Inc"
  homepage_intro: "Kots is a kubectl plugin to help manage Kubernetes Off-The-Shelf software"

  # matomo:
  #   host: "localhost:4000"
  #   site: "2"

  favicon: ""
  pagetitle: "Kots.io"
  permalink: "#"
  mainSections:
    - vendor
    - kotsadm
    - preflight
    - support-bundle
    - reference
menu:
  main:
    - Name: "Admin Console"
      Weight: 1
      URL: "/kotsadm/"
    - Name: "Vendor"
      Weight: 2
      URL: "/vendor/"
    - Name: "Preflight"
      Weight: 3
      URL: "/preflight/"
    - Name: "Support Bundle"
      Weight: 4
      URL: "/support-bundle/"
    - Name: "Reference"
      Weight: 5
      URL: "/reference/"
---
