---
baseURL: "https://kots.io"
languageCode: "en-us"
title: "Kots.io"
theme: "hugo-whisper-theme"
metadataformat: "yaml"
canonifyurls: true
relativeurls: true
description: "Documentation for Replicated KOTS."
googleAnalytics: ""

# Algoloia search
algolia:
  index: "prod_kotsio"
  appID: "RKUCTRIG38"

# Hugo configuration
pygmentsCodeFences: true
pygmentsStyle: "monokai"

staticDir:
    - ./static

Params:
  author: "Kots"
  copyright: "Replicated, Inc"
  homepage_intro: "KOTS is a kubectl plugin and admin console to help manage Kubernetes Off-The-Shelf software"
  logo:
    mobile: "/images/kots.svg"
  # matomo:
  #   host: "localhost:4000"
  #   site: "2"

  enable_anchor_link: true
  favicon: ""
  pagetitle: "Kots.io"
  permalink: "#"
  mainSections:
    - kots-cli
    - vendor
    - kotsadm
    - preflight
    - support-bundle
    - reference
    - v1beta1
    - release-notes
    - data-transmission-policy
menu:
  main:
    - Identifier: kots-cli
      Name: KOTS CLI
      Weight: 1
      URL: /kots-cli/getting-started
    - Identifier: kotsadm
      Name: Admin Console
      Weight: 2
      URL: /kotsadm/installing/installing-a-kots-app/
    - Identifier: reference
      Name: Reference
      Weight: 4
      URL: /reference/v1beta1/
    - Identifier: vendor
      Name: Vendor
      Weight: 3
      URL: /vendor/packaging/packaging-an-app
    - Identifier: release-notes
      Name: Release Notes
      Weight: 5
      URL: /release-notes/
---
