[[redirects]]
  from = "/kotsadm/snapshots/velero"
  to = "https://velero.io"
  status = 301
  force = true

[[redirects]]
  from = "/kotsadm/snapshots/velero-troubleshooting/"
  to = "https://velero.io/docs/main/troubleshooting/"
  status = 301
  force = true

[[redirects]]
  from = "/kotsadm/snapshots/restic/"
  to = "https://velero.io/docs/v1.3.2/restic/"
  status = 301
  force = true

[[redirects]]
  from = "/kotsadm/snapshots/restic-troubleshooting/"
  to = "https://velero.io/docs/main/restic/#troubleshooting"
  status = 301
  force = true

[[redirects]]
  from = "/kotsadm/snapshots/supported-providers/"
  to = "https://velero.io/docs/v1.3.2/supported-providers/"
  status = 301
  force = true

[[redirects]]
  from = "/kotsadm/snapshots/basic-install/"
  to = "https://velero.io/docs/v1.3.2/basic-install/#install-the-cli"
  status = 301
  force = true

[[redirects]]
  from = "/vendor/helm/helm-v3/"
  to = "/vendor/helm/helm-processing/"
  status = 301
  force = true

[[redirects]]
  from = "/kotsadm/snapshots/restic-deduplication/"
  to = "https://restic.readthedocs.io/en/latest/100_references.html#backups-and-deduplication"
  status = 301
  force = true
